services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "toto12345*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cesinet

  cesizen.ui:
    image: ${DOCKER_REGISTRY-}cesizenui
    build:
      context: .
      dockerfile: CesiZen.Ui/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CesiZenDb;User Id=sa;Password=toto12345*;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - cesinet

networks:
  cesinet:
