services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "toto12345*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cesinet
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P toto12345* -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  cesizen.ui:
    image: ${DOCKER_REGISTRY-}cesizenui
    build:
      context: .
      dockerfile: CesiZen.Ui/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CesiZenDb;User Id=sa;Password=toto12345*;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - cesinet

networks:
  cesinet:
