name: Snyk Security Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Analyse quotidienne à 2h du matin
    - cron: '0 2 * * *'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: |
        if [ -f "*.sln" ]; then
          SOLUTION=$(ls *.sln | head -1)
          echo "Restoring solution: $SOLUTION"
          dotnet restore "$SOLUTION"
        else
          find . -name "*.csproj" -exec dotnet restore {} \;
        fi

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/dotnet@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=*.sln

    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk.sarif

  snyk-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Snyk Code (SAST)
      uses: snyk/actions/dotnet@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --sarif-file-output=snyk-code.sarif

    - name: Upload Snyk Code results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk-code.sarif

  snyk-iac:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Snyk Infrastructure as Code
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk-iac.sarif

    - name: Upload Snyk IaC results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk-iac.sarif